### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by IceIce1ce** [Zyj061/snnTracker#1]
Hi author, congratulations on your TPAMI paper. When I run your tracking script, an error happened:
Traceback (most recent call last):
  File "/home/vsw/Desktop/SNNTracker/test_snntracker.py", line 16, in <module>
    from spkProc.tracking.snn_tracker import SNNTracker
  File "/home/vsw/Desktop/SNNTracker/spkProc/tracking/snn_tracker.py", line 13, in <module>
    from spkProc.filters.stp_filters_torch import STPFilter
ImportError: cannot import name 'STPFilter' from 'spkProc.filters.stp_filters_torch' (/home/vsw/Desktop/SNNTracker/spkProc/filters/stp_filters_torch.py)

**Comment by Zyj061** [comment]
Hi, thank you for your feedback and for trying out the code!

You are right — the error was caused by a missing file during my previous sync. I’ve just corrected the repository, and the STPFilter module should now be properly included.

Please pull the latest version and try running the tracking script again. Let me know if it works on your side.

**Comment by IceIce1ce** [comment]
Hi author, the code still cannot work. In test_snntracker.py, it need tracking_mot which is not available. Can you check your code again?
Traceback (most recent call last):
  File "/home/vsw/Desktop/snnTracker/test_snntracker.py", line 18, in <module>
    from tracking_mot import TrackingMetrics
ModuleNotFoundError: No module named 'tracking_mot'

**Comment by Zyj061** [comment]
We have removed the import module "tracking_mot", and it should work now. plz try again :-)

**Comment by IceIce1ce** [comment]
Hi author, the code is running normally now. Thanks for your help.
